exports.SCRAPE_API_BASE_URL = "https://dummyjson.com";

exports.SCRAPE_API_CATEGORY_LIST = [
  "womens-dresses",
  "womens-shoes",
  "mens-shirts",
  "mens-shoes",
  "mens-watches",
  "womens-watches",
  "womens-bags",
  "womens-jewellery",
];

exports.MATERIAL_LIST = [
  "Organic Cotton",
  "European Flax Linen",
  "Regenerated Nylon elastane",
  "Recycled Waterproof/ Breathable Face Fabric",
  "Recycled Polyester",
  "Silk",
  "Organic Linen",
  "Organic Cotton and Spandex",
  "renewable Wood",
  "Egyptian Cotton",
  "BCI Cotton Chambray",
];

exports.COLOR_LIST = [
  "Black, White, Heather Grey,Bone/Black",
  "Black, Bone, Bone/Black Check",
  "Shell, Sky",
  "Olive, Black",
  "Subtidal Blue, Nouveau Green, Smolder Blue, Black, Endless Blue, Buckhorn Green, Golden Caramel, Phosphorous Green, Wax Red",
  "Steam Blue, Journeys:Natural, Antique Pink, Wispy Green",
  "Pure White",
  "Dark Blue",
  "Blue, Black, Red",
  "Blue Stripe",
  "Black, White, Flame, Undyed natural",
  "Meteorite Black",
  "Black, Charcoal Heather, Blue Dusk, French Navy Heather, French Navy, Ivy, Medium Grey Heather",
  "Black, Dark Forest, East Coast Stripe, French Navy, Maroon",
  "Forest Green",
  "Faded Rose Pink",
  "Black, Mirage",
  "Blue",
];

exports.SIZE_LIST = [
  "XXS, XS, S, M, L, XL, XXL",
  "XXS, XS, S, M, L, XL, XXL",
  "XS, S, M, L, XL",
  "XS, S, M, L, XL",
  "XS, S, M, L, XL, XXL, 3XL",
  "XS, S, M, L, XL",
  "XXS, XS, S, M, L, XL",
  "XXS, XS, S, M, L, XL",
  "8, 10, 12, 14, 16",
  "8, 10, 12, 14, 16",
  "PP, PS, PM, PL, S, M, L, XL, XS, XXS, 1X, 2X, 3X",
  "PP,PS, PM, PL, S, M, L, XL, XS, XXS, 1X, 2X, 3X",
  "S, M, L, XL, XXL",
  "S, M, L, XL, XS",
  "S, M, L, XL",
  "S, M, L, XL, XS",
  "6, 8, 10, 12, 14, 16, 18",
  "6, 8, 10, 12, 14, 16, 18",
  "XS, S, M, L, XL, XXL",
  "XS, S, M, L, XL, XXL",
];
