module.exports = [
    {
        id: 1,
        name: 'Everlane',
        website_url: 'https://www.everlane.com',
        image_url: 'http://localhost:8080/images/everlane.png',
        description: 'Everlane is committed to radical transparency, offering ethically made, high-quality basics for men and women. Their focus on sustainable materials and transparent pricing sets them apart.',
        location: 'San Francisco, California, USA',
    },
    {
        id: 2,
        name: 'Reformation',
        website_url: 'https://www.thereformation.com',
        image_url: 'http://localhost:8080/images/thereformation.jpg',
        description: 'Reformation is known for its vintage-inspired aesthetic and commitment to sustainability. They use eco-friendly materials, prioritize fair labor practices, and offer extended size ranges.',
        location: 'Los Angeles, California, USA',
    },
    {
       	id: 3,
        name: 'Patagonia',
        website_url: 'https://www.patagonia.com',
        image_url: 'http://localhost:8080/images/patagonia.png',
        description: 'Patagonia is a pioneer in sustainable outdoor apparel. They focus on reducing their environmental footprint, promoting fair labor practices, and donating a portion of profits to environmental causes.',
        location: 'Ventura, California, USA',
    },
    {
        id: 4,
        name: 'Stella McCartney',
        website_url: 'https://www.stellamccartney.com',
        image_url: 'http://localhost:8080/images/stellamccartney.png',
        description: 'Stella McCartney is a luxury fashion brand known for its commitment to sustainability and ethical fashion practices. They use innovative materials and prioritize animal welfare.',
        location: 'London, United Kingdom',
    },
    {
        id: 5,
        name: 'People Tree',
        website_url: 'https://www.peopletree.co.uk',
        image_url: 'http://localhost:8080/images/peopletree.jpg',
        description: 'People Tree is a pioneer in Fair Trade fashion, offering clothing made from sustainable materials and produced by artisans in developing countries under fair labor conditions.',
        location: 'London, United Kingdom',
    },
    {
        id: 6,
        name: 'Eileen Fisher',
        website_url: 'https://www.eileenfisher.com',
        image_url: 'http://localhost:8080/images/eileenfisher.jpg',
        description: 'Eileen Fisher is known for its timeless designs and commitment to sustainability. They use organic and recycled materials and focus on reducing waste throughout their supply chain.',
        location: 'New York, USA',
    },
    {
        id: 7,
        name: 'Tentree',
        website_url: 'https://www.tentree.com',
        image_url: 'http://localhost:8080/images/tentree.png',
        description: 'Tentree is a sustainable apparel brand known for planting ten trees for every item purchased. They offer a range of clothing made from eco-friendly materials.',
        location: 'Vancouver, British Columbia, Canada',
    },
    {
        id: 8,
  	    name: 'Pact',
  	    website_url: 'https://wearpact.com',
        image_url: 'http://localhost:8080/images/wearpact.jpg',
  	    description: 'Pact is committed to creating clothing that is kind to the planet and its people. They use organic cotton and other sustainable materials to produce comfortable and ethically-made clothing.',
  	    location: 'Boulder, Colorado, USA',
    },
    {
        id: 9,
        name: 'Thought',
        website_url: 'https://www.wearethought.com',
        image_url: 'http://localhost:8080/images/wearethought.png',
        description: 'Thought is a sustainable fashion brand offering contemporary clothing made from natural, eco-friendly materials such as organic cotton, bamboo, and hemp.',
        location: 'London, United Kingdom',
    },
    {
        id: 10,
        name: 'Kotn',
        website_url: 'https://www.kotn.com',
        image_url: 'http://localhost:8080/images/kotn.png',
        description: 'Kotn is a Canadian brand specializing in ethically made essentials crafted from Egyptian cotton. They prioritize transparency and invest in community development projects.',
        location: 'Toronto, Ontario, Canada',
    },
];